version: "3.9"

services:

  django:
    container_name: Django
    build: 
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
    - 8008:8000
    volumes:
    - ./:/app
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine3.16
    container_name: postgres
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=base
      - POSTGRES_USER=magoreal
      - POSTGRES_PASSWORD=ojalaque
    volumes:
      - ./db:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./:/app
    depends_on:
      - django

  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: 'magoreal4@gmail.com'
  #     PGADMIN_DEFAULT_PASSWORD: 'ojalaque'
  #   ports:
  #     - "5050:80"

  # rabbitmq:
  #   image: "rabbitmq:alpine"
  #   container_name: rabbitmq
  #   healthcheck:
  #     test: rabbitmq-diagnostics -q ping
  #     interval: 30s
  #     timeout: 30s
  #     retries: 3

  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data


# volumes:
#     postgres-data:
#     redis-data:

