# Generated by Django 4.2.11 on 2024-04-15 03:20

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='titulo')),
                ('description', models.TextField(blank=True, default='', max_length=250, verbose_name='contenido')),
                ('svg', models.FileField(blank=True, default='', upload_to='icon/', validators=[main.validators.validate_file_extension])),
                ('display', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Nuestros Servicios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255)),
                ('description_name', models.TextField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
    ]
