# Generated by Django 4.2.11 on 2024-04-15 03:36

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alcance_siteconfiguration_delete_principal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='description_name',
            new_name='site_description',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.FileField(blank=True, default='', upload_to='logo/', validators=[main.validators.validate_file_extension_svg]),
        ),
    ]
