# Generated by Django 4.2.11 on 2024-04-15 03:59

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_description_name_siteconfiguration_site_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.FileField(blank=True, default='', upload_to='svg/', validators=[main.validators.validate_file_extension_svg]),
        ),
    ]
